import { Button } from "@/components/ui/button";
import Calendar from "@/components/ui/calendar";
import DateTime from "@/components/ui/dateTime";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@radix-ui/react-select";
import { title } from "process";

export const initialDetails = [
  {
    id: 1,
    firstName: "Aarav",
    lastName: "Sharma",
    primaryNumber: 9876543210,
    alternateNumber: 9123456780,
    status: "Interested",
    email: "aarav.sharma@example.com",
    dateOfBirth: "1998-01-15",
    location: "Delhi",
    course: "Piano",
    mode: "Online",
    gender: "Male",
    source: "Instagram",
    pastExperience: "No",
    whyMusic: "Relaxation",
  },
  {
    id: 2,
    firstName: "Meera",
    lastName: "Iyer",
    primaryNumber: 9812345678,
    alternateNumber: 9887766554,
    status: "Demo Taken",
    email: "meera.iyer@example.com",
    dateOfBirth: "1995-05-23",
    location: "Bangalore",
    course: "Western Vocal",
    mode: "Offline",
    gender: "Female",
    source: "YouTube",
    pastExperience: "Yes",
    whyMusic: "Career aspirations",
  },
  {
    id: 3,
    firstName: "Rahul",
    lastName: "Verma",
    primaryNumber: 9898989898,
    alternateNumber: 9777666555,
    status: "Converted",
    email: "rahul.verma@example.com",
    dateOfBirth: "1990-11-11",
    location: "Hyderabad",
    course: "Drums",
    mode: "Online",
    gender: "Male",
    source: "Friend Referral",
    pastExperience: "No",
    whyMusic: "Passion",
  },
  {
    id: 4,
    firstName: "Sneha",
    lastName: "Patel",
    primaryNumber: 9345678923,
    alternateNumber: 9223344556,
    status: "First Call",
    email: "sneha.patel@example.com",
    dateOfBirth: "2000-03-19",
    location: "Ahmedabad",
    course: "Violin",
    mode: "Offline",
    gender: "Female",
    source: "Social Media",
    pastExperience: "No",
    whyMusic: "Therapy",
  },
  {
    id: 5,
    firstName: "Dev",
    lastName: "Kumar",
    primaryNumber: 9765432187,
    alternateNumber: 9445566778,
    status: "Not Interested",
    email: "dev.kumar@example.com",
    dateOfBirth: "1985-12-05",
    location: "Chennai",
    course: "Cello",
    mode: "Online",
    gender: "Male",
    source: "Website",
    pastExperience: "Yes",
    whyMusic: "Performance goals",
  },
  {
    id: 6,
    firstName: "Ananya",
    lastName: "Singh",
    primaryNumber: 9321009834,
    alternateNumber: 9080706050,
    status: "Visited",
    email: "ananya.singh@example.com",
    dateOfBirth: "1999-07-30",
    location: "Pune",
    course: "Keyboard",
    mode: "Offline",
    gender: "Female",
    source: "Flyer",
    pastExperience: "No",
    whyMusic: "Hobby",
  },
  {
    id: 7,
    firstName: "Kabir",
    lastName: "Desai",
    primaryNumber: 9988776655,
    alternateNumber: 9111222333,
    status: "Second Call",
    email: "kabir.desai@example.com",
    dateOfBirth: "1993-04-17",
    location: "Mumbai",
    course: "Guitar",
    mode: "Online",
    gender: "Male",
    source: "Social Media",
    pastExperience: "Yes",
    whyMusic: "Band practice",
  },
  {
    id: 8,
    firstName: "Riya",
    lastName: "Kapoor",
    primaryNumber: 9876078945,
    alternateNumber: 9362758493,
    status: "Demo Scheduled",
    email: "riya.kapoor@example.com",
    dateOfBirth: "1997-06-12",
    location: "Kolkata",
    course: "Ukulele",
    mode: "Offline",
    gender: "Female",
    source: "Google Search",
    pastExperience: "No",
    whyMusic: "Try something new",
  },
  {
    id: 9,
    firstName: "Arjun",
    lastName: "Rao",
    primaryNumber: 9012345678,
    alternateNumber: 9123456700,
    status: "Third Call",
    email: "arjun.rao@example.com",
    dateOfBirth: "1991-09-09",
    location: "Nagpur",
    course: "Wind Instruments",
    mode: "Online",
    gender: "Male",
    source: "Social Media",
    pastExperience: "Yes",
    whyMusic: "Professional training",
  },
  {
    id: 10,
    firstName: "Tanvi",
    lastName: "Joshi",
    primaryNumber: 9123981239,
    alternateNumber: 9823948123,
    status: "Fresh Lead",
    email: "tanvi.joshi@example.com",
    dateOfBirth: "2002-10-21",
    location: "Jaipur",
    course: "Other",
    mode: "Online",
    gender: "Female",
    source: "Facebook",
    pastExperience: "No",
    whyMusic: "Explore new interests",
  },
];

export const fields = [
  { key: "firstName", label: "First Name", type: "input", value: "fName" },
  { key: "lastName", label: "Last Name", type: "input" },
  { key: "primaryNumber", label: "Primary number", type: "input" },
  { key: "alternateNumber", label: "Alternate number", type: "input" },
  {
    key: "status",
    label: "Status",
    type: "select",
    options: [
      "Fresh Lead",
      "First Call",
      "Second Call",
      "Third Call",
      "Visiting",
      "Visited",
      "Interested",
      "Demo Scheduled",
      "Demo Taken",
      "Not Interested",
      "Converted",
    ],
  },
  { key: "email", label: "Email", type: "input" },
  { key: "dateOfBirth", label: "Date of Birth", type: "date" },
  { key: "location", label: "Location", type: "input" },
  {
    key: "course",
    label: "Course",
    type: "select",
    options: [
      "Drums",
      "Piano",
      "Guitar",
      "Western Vocal",
      "Violin",
      "Cello",
      "Ukulele",
      "Keyboard",
      "Wind Instruments",
      "Other",
    ],
  },
  {
    key: "mode",
    label: "Mode",
    type: "select",
    options: ["Online", "Offline"],
  },
  {
    key: "gender",
    label: "Gender",
    type: "select",
    options: ["Female", "Male", "Other"],
  },
  {
    key: "source",
    label: "Source",
    type: "select",
    options: ["Female", "Male", "Other"],
  },
  {
    key: "pastExperience",
    label: "Past Experience",
    type: "select",
    options: ["Yes", "No"],
  },
  { key: "whyMusic", label: "Why Music?", type: "input" },
];

export const activityTableLogs = [
  { label: "Callback Date & Time", type: DateTime },
  // { label: "Enquiry Message", type: Textarea },
  {
    label: "Status",
    type: Select,
    options: [
      "Fresh Lead",
      "First Call",
      "Second Call",
      "Third Call",
      "Visiting",
      "Visited",
      "Interested",
      "Demo Scheduled",
      "Demo Taken",
      "Not Interested",
      "Converted",
    ],
  },
];

export const leadsTablecolumns = [
  {
    title: "Name",
    colspan: 3,
  },
  {
    title: "Phone",
    colspan: 3,
  },
  {
    title: "Status",
    colspan: 2,
  },
  {
    title: "Course",
    colspan: 2,
  },
];

export const createCourseFields = [
  {
    label: "Course Name",
    type: Input,
    value: "courseName",
  },
  {
    label: "Course Description",
    type: Input,
    value: "courseDescription",
  },
  {
    label: "Image",
    type: Input,
    value: "courseImage",
  },
  {
    label: "Fees Type",
    type: Select,
    value: "feesType",
    options: ["One time", "Subscription"],
    // options: [
    //   { label: "One time", value: "oneTime" },
    //   { label: "Subscription", value: "subscription" },
    // ],
  },
  {
    label: "Add a Plan",
    type: Input,
    value: "planName",
  },
  {
    label: "Billing Cycle",
    type: Select,
    value: "billingCycle",
    options: ["Number of Days", "Number of Weeks", "Number of Months"],
  },
  {
    label: "Batch Type",
    type: Select,
    value: "batchType",
    options: ["VIP", "Group"],
  },
  {
    label: "Batches/week",
    type: Input,
    value: "batchesPerWeek",
  },
  {
    label: "Price",
    type: Input,
    value: "price",
  },
  // {
  //   label: "",
  //   type: Button,
  //   value: "upload",
  //   title: "Upload",
  // },
];

export const userActivityLogFields = [
  { key: "callbackDateTime", label: "Callback Date & Time" },
  { key: "status", label: "Status" },
  { key: "createdBy", label: "Created By" },
  { key: "enquiryMessage", label: "Enquiry Message" },
  { key: "loggedAt", label: "Logged At" },
];
export const userActivityLogs = [
  {
    id: 1,
    callbackDateTime: "2025-04-15T14:30:00Z",
    status: "Scheduled",
    loggedAt: "2025-04-15T14:32:10Z",
    createdBy: "Milton Lance",
    enquiryMessage:
      "Please call me after 2 PM. I'm interested in online drums class.Please call me after 2 PM. I'm interested in online drums class.Please call me after 2 PM. I'm interested in online drums class.Please call me after 2 PM. I'm interested in online drums class.Please call me after 2 PM. I'm interested in online drums class.Please call me after 2 PM. I'm interested in online drums class.",
  },
  {
    id: 2,
    callbackDateTime: "2025-04-14T10:00:00Z",
    status: "Interested",
    enquiryMessage: "Looking to join from next week. Need more details.",
    loggedAt: "2025-04-14T10:02:45Z",
    createdBy: "Milton Lance",
  },
  {
    id: 3,
    callbackDateTime: "2025-04-13T18:45:00Z",
    status: "Follow-up Needed",
    enquiryMessage: "Missed last call. Can we reschedule?",
    loggedAt: "2025-04-13T18:46:21Z",
    createdBy: "Milton Lance",
  },
  {
    id: 4,
    callbackDateTime: "2025-04-12T12:15:00Z",
    status: "Converted",
    enquiryMessage: "Enrolled in the Guitar Beginner course.",
    loggedAt: "2025-04-12T12:17:00Z",
    createdBy: "Milton Lance",
  },
];
